/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_system_NativeUtils */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_NativeUtils
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_NativeUtils
 * Method:    freeByteBuffer
 * Signature: ([Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_NativeUtils_freeByteBuffer
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
