/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    nsystemFonts
 * Signature: ()[Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3Font;
 */
JNIEXPORT jobjectArray JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_nsystemFonts
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    nhideXWindowButtons
 * Signature: (JJZZ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_nhideXWindowButtons
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
