/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    nalloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_nalloc
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    nfree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_nfree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    ninit
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_ninit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    nloop
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_nloop
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    nupdate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_nupdate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    nexit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_nexit
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    nsetTooltip
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_nsetTooltip
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    nsetIcon
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_nsetIcon
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray
 * Method:    nsetItems
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3Tray_nsetItems
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
