/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nalloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nalloc
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nfree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nfree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nsetIcon
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nsetIcon
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nsetText
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nsetText
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nsetDisabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nsetDisabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nsetChecked
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nsetChecked
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nsetRadioCheck
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nsetRadioCheck
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nsetType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nsetType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nsetItems
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nsetItems
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nisDisabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nisDisabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nisChecked
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nisChecked
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nisRadioCheck
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nisRadioCheck
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    ngetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_ngetType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem
 * Method:    nsetCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_nsetCallback
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
