/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_OnClickListener */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_OnClickListener
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_factory_Lwjgl3TrayItem_OnClickListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
