/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    getSystemFonts
 * Signature: ()[Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3FontHandle;
 */
JNIEXPORT jobjectArray JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_getSystemFonts
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    getDefaultFont
 * Signature: ()Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3FontHandle;
 */
JNIEXPORT jobject JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_getDefaultFont
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    grabPointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_grabPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    ungrabPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_ungrabPointer
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    enableWindow
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_enableWindow
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
