/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    getSystemFonts
 * Signature: ()[Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3FontHandle;
 */
JNIEXPORT jobjectArray JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_getSystemFonts
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    getDefaultFont
 * Signature: ()Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3FontHandle;
 */
JNIEXPORT jobject JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_getDefaultFont
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    grabPointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_grabPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    ungrabPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_ungrabPointer
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    setWindowIsDialog
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_setWindowIsDialog
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    setWindowIsNormal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_setWindowIsNormal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    setWindowIsTooltip
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_setWindowIsTooltip
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    setWindowIsPopup
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_setWindowIsPopup
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_windows_WindowsNatives_open
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
