/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    getSystemFonts
 * Signature: ()[Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3FontHandle;
 */
JNIEXPORT jobjectArray JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_getSystemFonts
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    getGtkDefaultFont
 * Signature: ()Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3FontHandle;
 */
JNIEXPORT jobject JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_getGtkDefaultFont
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    hideXWindowButtons
 * Signature: (JJZZ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_hideXWindowButtons
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    setXWindowIsDialog
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_setXWindowIsDialog
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    setXWindowIsNormal
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_setXWindowIsNormal
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    setXWindowIsTooltip
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_setXWindowIsTooltip
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    setXWindowIsPopup
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_setXWindowIsPopup
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    XGrabPointer
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_XGrabPointer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    XUngrabPointer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_XUngrabPointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
