/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives */

#ifndef _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
#define _Included_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    nsystemFonts
 * Signature: ()[Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3Font;
 */
JNIEXPORT jobjectArray JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_nsystemFonts
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    nhideXWindowButtons
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_nhideXWindowButtons
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    ngetGtkDefaultFont
 * Signature: ()Lcom/anyicomplex/gdx/dwt/backends/lwjgl3/toolkit/Lwjgl3Font;
 */
JNIEXPORT jobject JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_ngetGtkDefaultFont
  (JNIEnv *, jclass);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    setXWindowIsDialog
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_setXWindowIsDialog
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives
 * Method:    unsetXWindowIsDialog
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_anyicomplex_gdx_dwt_backends_lwjgl3_system_linux_LinuxNatives_unsetXWindowIsDialog
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
